### ISSUE TITLE
我想问下怎么修改生成次数.

### ISSUE THREAD

**Issue by cuihua0** [Herumw/Train-computer-to-imitate-world-famous-paintings#1]
就是每张图都只能生成16次，第16次就完了。是不是还可以增加次数让图片更精确。

**Comment by cuihua0** [comment]
我是新手

**Comment by Herumw** [comment]
neural_style_transfer.py打开，里面有行代码，如下面：parser.add_argument('--iter', type=int, default=16, required=False, help='Number of iterations to run.')，只要把16改下就好啦，可以改成任意数字
